version: '3.8'

services:
  spring-app:
    image: maven:3.8.8-eclipse-temurin-17
    container_name: spring-app
    volumes:
      - .:/app
    working_dir: /app
    command: mvn clean spring-boot:run
    ports:
      - "9091:9091"
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:socialDb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_PORT: 9091
      SERVER_SERVLET_CONTEXT_PATH: /social/api/v1
    networks:
      - spring-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
