version: '3.8'

services:
  # Spring Boot application service
  app:
    build: . # Build the Docker image using the Dockerfile in the current directory
    container_name: spring-boot-caching-app
    ports:
      - "9091:9091" # Map host port 8080 to container port 8080
    depends_on:
      - redis # Ensure Redis starts before the app
    networks:
      - spring-network # Connect to the custom network

  # Redis service
  redis:
    image: redis:7.0-alpine # Use the official Redis image
    container_name: redis
    ports:
      - "6379:6379" # Map host port 6379 to container port 6379
    networks:
      - spring-network # Connect to the custom network

# Define a custom bridge network for the services
networks:
  spring-network:
    driver: bridge
