server:
  port: 9091
  servlet:
    context-path: /social/api/v1


# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:socialDb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
